### ISSUE TITLE
Does not work with the latest version of terraform 1.2.8

### ISSUE THREAD

**Issue by jarrettj** [aws-samples/amazon-guardduty-for-aws-organizations-with-terraform#2]
Hi,

Good day..

Followed the instructions up to "Run the setup script." step. When executing:

bash scripts/full-setup.sh, I get the following:
```
Creating the Delegated admin account role
╷
│ Error: Unsupported Terraform Core version
│ 
│   on versions.tf line 19, in terraform:
│   19:   required_version = "= 0.14.6"
│ 
│ This configuration does not support Terraform version 1.2.8. To proceed, either choose another supported Terraform version or update this version
```

Should we downgrade our terraform version? Thanks.

Regards,
Jarrett

**Comment by aarthkan** [comment]
Hi Jarrett,
There is no need to downgrade your Terraform version. There are 2 ways to resolve this error. You can change the following line:
  required_version = "= 0.14.6"
either to the _generic_ option (which continues to support terraform upgrades in the future)
  required_version = ">= 0.14.6"
or to the _specific_ option to match the terraform version you have installed (1.2.8 as per your error message)
  required_version = "= 1.2.8"
The above change needs to be done in the following files:
a) create-delegatedadmin-acct-role/versions.tf
b) create-gd-bucket-and-key/modules/s3-bucket-create/versions.tf
c) create-gd-bucket-and-key/versions.tf
d) create-logging-acct-role/versions.tf
e) enable-gd/modules/versions.tf
f) enable-gd/versions.tf
g) import-org/versions.tf

The choice of option depends on the uniformity of Terraform versions across your environment.
I tested the _generic_ option with version 1.2.8 and it works fine.
Please let me know how it goes at your end.

Regards,
Aarthi

**Comment by jarrettj** [comment]
Awesome, thanks for the prompt response! Will do.
